--------------------------------------------------------
--  Fichier créé - jeudi-mai-30-2024   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence ARTICLE_ID_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "DHIA"."ARTICLE_ID_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 301 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence ASSOCIATION_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "DHIA"."ASSOCIATION_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 41 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence TABLE2_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "DHIA"."TABLE2_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table ARTICLE
--------------------------------------------------------

  CREATE TABLE "DHIA"."ARTICLE" 
   (	"ID_ARTICLE" NUMBER, 
	"DOMAINE_ARTICLE" VARCHAR2(255 BYTE), 
	"NOM_ARTICLE" VARCHAR2(255 BYTE), 
	"DATE_CREATION_ARTICLE" VARCHAR2(255 BYTE), 
	"TYPE_ARTICLE" VARCHAR2(255 BYTE), 
	"DIMENSION_ARTICLE" VARCHAR2(255 BYTE), 
	"POIDS_ARTICLE" NUMBER, 
	"PRIX_ARTICLE" NUMBER, 
	"DESCRIPTION_ARTICLE" VARCHAR2(4000 BYTE), 
	"CHEMIN_IMAGE" VARCHAR2(4000 BYTE), 
	"ID_ARTISTE" NUMBER, 
	"ID_VISITEUR" NUMBER, 
	"NBVU" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table ASSOCIATION
--------------------------------------------------------

  CREATE TABLE "DHIA"."ASSOCIATION" 
   (	"ID" NUMBER, 
	"NOM" VARCHAR2(255 BYTE), 
	"ADRESS" VARCHAR2(255 BYTE), 
	"BUDGET" NUMBER, 
	"DESCRIPTION" VARCHAR2(255 BYTE), 
	"TYPE" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CONTROLLER
--------------------------------------------------------

  CREATE TABLE "DHIA"."CONTROLLER" 
   (	"IDEMPLOYEE" NUMBER, 
	"IDEVENT" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table EMPLOYEE
--------------------------------------------------------

  CREATE TABLE "DHIA"."EMPLOYEE" 
   (	"ID" NUMBER, 
	"NAME" VARCHAR2(255 BYTE), 
	"LASTNAME" VARCHAR2(255 BYTE), 
	"ADDRESS" VARCHAR2(255 BYTE), 
	"SEX" VARCHAR2(255 BYTE), 
	"DATEBIRTH" VARCHAR2(255 BYTE), 
	"MAIL" VARCHAR2(255 BYTE), 
	"FUNCTION" VARCHAR2(255 BYTE), 
	"PASSWORD" VARCHAR2(255 BYTE), 
	"PHONENUMBER" VARCHAR2(255 BYTE), 
	"IMAGE" BLOB
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 
 LOB ("IMAGE") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table EVENEMENT
--------------------------------------------------------

  CREATE TABLE "DHIA"."EVENEMENT" 
   (	"ID_EVENT" NUMBER, 
	"EVENT_NOUN" VARCHAR2(255 BYTE), 
	"LOCATION" VARCHAR2(255 BYTE), 
	"START_D" DATE, 
	"END_D" DATE, 
	"START_H" TIMESTAMP (6), 
	"END_H" TIMESTAMP (6), 
	"PRICE_TICK" FLOAT(126), 
	"DESCRIPTION" VARCHAR2(255 BYTE), 
	"NB_EMPLOYEE" NUMBER, 
	"AFFICHE" BLOB, 
	"RFID" VARCHAR2(255 BYTE), 
	"ETAT" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 
 LOB ("AFFICHE") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table GUEST
--------------------------------------------------------

  CREATE TABLE "DHIA"."GUEST" 
   (	"CIN" NUMBER(11,0), 
	"NAME" VARCHAR2(255 BYTE), 
	"AGE" NUMBER(3,0), 
	"GENDER" VARCHAR2(255 BYTE), 
	"ADDRESS" VARCHAR2(255 BYTE), 
	"PHONE" NUMBER(11,0), 
	"EMAIL" VARCHAR2(255 BYTE), 
	"IMAGE" BLOB
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 
 LOB ("IMAGE") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table PARTICIPER
--------------------------------------------------------

  CREATE TABLE "DHIA"."PARTICIPER" 
   (	"IDGUEST" NUMBER, 
	"IDEVENT" NUMBER, 
	"PRESENCE" NUMBER(1,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table SPONSORISER
--------------------------------------------------------

  CREATE TABLE "DHIA"."SPONSORISER" 
   (	"IDEVENT" NUMBER, 
	"IDASSOCIATION" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table TABLE1
--------------------------------------------------------

  CREATE TABLE "DHIA"."TABLE1" 
   (	"CIN" NUMBER, 
	"TEL" NUMBER, 
	"NOM" VARCHAR2(20 BYTE), 
	"PRENOM" VARCHAR2(20 BYTE), 
	"ADRESSE" VARCHAR2(20 BYTE), 
	"MAIL" VARCHAR2(20 BYTE), 
	"DOMAINE" VARCHAR2(20 BYTE), 
	"DESCRIPTION" VARCHAR2(20 BYTE), 
	"SEXE" VARCHAR2(20 BYTE), 
	"IMAGE" BLOB
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 
 LOB ("IMAGE") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
REM INSERTING into DHIA.ARTICLE
SET DEFINE OFF;
Insert into DHIA.ARTICLE (ID_ARTICLE,DOMAINE_ARTICLE,NOM_ARTICLE,DATE_CREATION_ARTICLE,TYPE_ARTICLE,DIMENSION_ARTICLE,POIDS_ARTICLE,PRIX_ARTICLE,DESCRIPTION_ARTICLE,CHEMIN_IMAGE,ID_ARTISTE,ID_VISITEUR,NBVU) values ('281','poterie','Vase','09/05/2024','decoration','88','50','50','vase aiesetic','C:/Users/meddh/Downloads/emna2 (1).png','12345678','1','24');
REM INSERTING into DHIA.ASSOCIATION
SET DEFINE OFF;
Insert into DHIA.ASSOCIATION (ID,NOM,ADRESS,BUDGET,DESCRIPTION,TYPE) values ('1','aaa','51.507353422269695,-0.13048949737651583','25','dddd','Private');
Insert into DHIA.ASSOCIATION (ID,NOM,ADRESS,BUDGET,DESCRIPTION,TYPE) values ('2','ass','51.507807509034556,-0.12701335449369822','66','bb','Public');
REM INSERTING into DHIA.CONTROLLER
SET DEFINE OFF;
REM INSERTING into DHIA.EMPLOYEE
SET DEFINE OFF;
Insert into DHIA.EMPLOYEE (ID,NAME,LASTNAME,ADDRESS,SEX,DATEBIRTH,MAIL,FUNCTION,PASSWORD,PHONENUMBER) values ('13290166','farah','hassen','gabes','Femelle','01-JAN-99','farahhassen96@gmail.com','Director','62323862653161653631653438343138363032326261383738346365616638663733653133616364376631643263616261666436373930623232643636613232','29703391');
Insert into DHIA.EMPLOYEE (ID,NAME,LASTNAME,ADDRESS,SEX,DATEBIRTH,MAIL,FUNCTION,PASSWORD,PHONENUMBER) values ('11675604','dhia','chaouachi','tunis','Male','01-JAN-00','mohameddhia@gmail.com','Director','31653034316633383137313765666435663336353264656531393031663838373733383833376361666331643066346665363238323530323863666532626132','95020708');
REM INSERTING into DHIA.EVENEMENT
SET DEFINE OFF;
Insert into DHIA.EVENEMENT (ID_EVENT,EVENT_NOUN,LOCATION,START_D,END_D,START_H,END_H,PRICE_TICK,DESCRIPTION,NB_EMPLOYEE,RFID,ETAT) values ('1','Fantasi','tunis',to_date('05/08/24','DD/MM/RR'),to_date('09/09/24','DD/MM/RR'),to_timestamp('17/05/24 10:00:00,000000000','DD/MM/RR HH24:MI:SSXFF'),to_timestamp('17/05/24 15:00:00,000000000','DD/MM/RR HH24:MI:SSXFF'),'30','racisme','3','23 CD E8 A6','n''est pas commence');
REM INSERTING into DHIA.GUEST
SET DEFINE OFF;
Insert into DHIA.GUEST (CIN,NAME,AGE,GENDER,ADDRESS,PHONE,EMAIL) values ('1',null,null,null,null,null,null);
Insert into DHIA.GUEST (CIN,NAME,AGE,GENDER,ADDRESS,PHONE,EMAIL) values ('11675604','Mohamed dhia chaouachi','21','Man','tunis','95020708','mohameddhia.chaouachi@esprit.tn');
Insert into DHIA.GUEST (CIN,NAME,AGE,GENDER,ADDRESS,PHONE,EMAIL) values ('10258935','menyar labidi','22','Woman','ariana','92364789','menyar.labidi@gmail.com');
REM INSERTING into DHIA.PARTICIPER
SET DEFINE OFF;
Insert into DHIA.PARTICIPER (IDGUEST,IDEVENT,PRESENCE) values ('11675604','1','0');
Insert into DHIA.PARTICIPER (IDGUEST,IDEVENT,PRESENCE) values ('10258935','1','1');
REM INSERTING into DHIA.SPONSORISER
SET DEFINE OFF;
REM INSERTING into DHIA.TABLE1
SET DEFINE OFF;
Insert into DHIA.TABLE1 (CIN,TEL,NOM,PRENOM,ADRESSE,MAIL,DOMAINE,DESCRIPTION,SEXE) values ('12345678','98824156','Ayoub','Tout','Tunis','ayoub@gmail.com','peinture','peintre','Man');
--------------------------------------------------------
--  DDL for Index EVENEMENT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DHIA"."EVENEMENT_PK" ON "DHIA"."EVENEMENT" ("ID_EVENT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index GUEST_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DHIA"."GUEST_PK" ON "DHIA"."GUEST" ("CIN") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PARTICIPER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DHIA"."PARTICIPER_PK" ON "DHIA"."PARTICIPER" ("IDGUEST", "IDEVENT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index TABLE2_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DHIA"."TABLE2_PK" ON "DHIA"."EMPLOYEE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index CONTROLLER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DHIA"."CONTROLLER_PK" ON "DHIA"."CONTROLLER" ("IDEMPLOYEE", "IDEVENT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_ARTIST_ID
--------------------------------------------------------

  CREATE UNIQUE INDEX "DHIA"."PK_ARTIST_ID" ON "DHIA"."TABLE1" ("CIN") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SPONSORISER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DHIA"."SPONSORISER_PK" ON "DHIA"."SPONSORISER" ("IDEVENT", "IDASSOCIATION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index ASSOCIATION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DHIA"."ASSOCIATION_PK" ON "DHIA"."ASSOCIATION" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Trigger ARTICLE_ID_TRIGGER
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "DHIA"."ARTICLE_ID_TRIGGER" 
BEFORE INSERT ON Article
FOR EACH ROW
BEGIN
    SELECT article_id_seq.NEXTVAL INTO :new.id_article FROM dual;
END;

/
ALTER TRIGGER "DHIA"."ARTICLE_ID_TRIGGER" ENABLE;
--------------------------------------------------------
--  DDL for Trigger ASSOCIATION_TRIGGER
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "DHIA"."ASSOCIATION_TRIGGER" 
BEFORE INSERT ON ASSOCIATION
FOR EACH ROW
BEGIN
    SELECT association_seq.NEXTVAL
    INTO :new.id
    FROM dual;
END;
/
ALTER TRIGGER "DHIA"."ASSOCIATION_TRIGGER" ENABLE;
--------------------------------------------------------
--  Constraints for Table ARTICLE
--------------------------------------------------------

  ALTER TABLE "DHIA"."ARTICLE" ADD PRIMARY KEY ("ID_ARTICLE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TABLE1
--------------------------------------------------------

  ALTER TABLE "DHIA"."TABLE1" ADD CONSTRAINT "PK_ARTIST_ID" PRIMARY KEY ("CIN")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table GUEST
--------------------------------------------------------

  ALTER TABLE "DHIA"."GUEST" MODIFY ("CIN" NOT NULL ENABLE);
  ALTER TABLE "DHIA"."GUEST" ADD CONSTRAINT "GUEST_PK" PRIMARY KEY ("CIN")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ASSOCIATION
--------------------------------------------------------

  ALTER TABLE "DHIA"."ASSOCIATION" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "DHIA"."ASSOCIATION" ADD CONSTRAINT "ASSOCIATION_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PARTICIPER
--------------------------------------------------------

  ALTER TABLE "DHIA"."PARTICIPER" MODIFY ("IDGUEST" NOT NULL ENABLE);
  ALTER TABLE "DHIA"."PARTICIPER" MODIFY ("IDEVENT" NOT NULL ENABLE);
  ALTER TABLE "DHIA"."PARTICIPER" ADD CONSTRAINT "PARTICIPER_PK" PRIMARY KEY ("IDGUEST", "IDEVENT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CONTROLLER
--------------------------------------------------------

  ALTER TABLE "DHIA"."CONTROLLER" MODIFY ("IDEMPLOYEE" NOT NULL ENABLE);
  ALTER TABLE "DHIA"."CONTROLLER" MODIFY ("IDEVENT" NOT NULL ENABLE);
  ALTER TABLE "DHIA"."CONTROLLER" ADD CONSTRAINT "CONTROLLER_PK" PRIMARY KEY ("IDEMPLOYEE", "IDEVENT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table EMPLOYEE
--------------------------------------------------------

  ALTER TABLE "DHIA"."EMPLOYEE" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "DHIA"."EMPLOYEE" ADD CONSTRAINT "TABLE2_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table SPONSORISER
--------------------------------------------------------

  ALTER TABLE "DHIA"."SPONSORISER" MODIFY ("IDEVENT" NOT NULL ENABLE);
  ALTER TABLE "DHIA"."SPONSORISER" MODIFY ("IDASSOCIATION" NOT NULL ENABLE);
  ALTER TABLE "DHIA"."SPONSORISER" ADD CONSTRAINT "SPONSORISER_PK" PRIMARY KEY ("IDEVENT", "IDASSOCIATION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table EVENEMENT
--------------------------------------------------------

  ALTER TABLE "DHIA"."EVENEMENT" MODIFY ("ID_EVENT" NOT NULL ENABLE);
  ALTER TABLE "DHIA"."EVENEMENT" ADD CONSTRAINT "EVENEMENT_PK" PRIMARY KEY ("ID_EVENT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ARTICLE
--------------------------------------------------------

  ALTER TABLE "DHIA"."ARTICLE" ADD CONSTRAINT "FK_ID_ARTISTE" FOREIGN KEY ("ID_ARTISTE")
	  REFERENCES "DHIA"."TABLE1" ("CIN") ENABLE;
  ALTER TABLE "DHIA"."ARTICLE" ADD CONSTRAINT "FK_ID_VISITEUR" FOREIGN KEY ("ID_VISITEUR")
	  REFERENCES "DHIA"."GUEST" ("CIN") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CONTROLLER
--------------------------------------------------------

  ALTER TABLE "DHIA"."CONTROLLER" ADD CONSTRAINT "CONTROLLER_FK1" FOREIGN KEY ("IDEMPLOYEE")
	  REFERENCES "DHIA"."EMPLOYEE" ("ID") ENABLE;
  ALTER TABLE "DHIA"."CONTROLLER" ADD CONSTRAINT "CONTROLLER_FK2" FOREIGN KEY ("IDEMPLOYEE")
	  REFERENCES "DHIA"."EVENEMENT" ("ID_EVENT") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PARTICIPER
--------------------------------------------------------

  ALTER TABLE "DHIA"."PARTICIPER" ADD CONSTRAINT "PARTICIPER_FK1" FOREIGN KEY ("IDEVENT")
	  REFERENCES "DHIA"."EVENEMENT" ("ID_EVENT") ENABLE;
  ALTER TABLE "DHIA"."PARTICIPER" ADD CONSTRAINT "PARTICIPER_FK2" FOREIGN KEY ("IDGUEST")
	  REFERENCES "DHIA"."GUEST" ("CIN") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SPONSORISER
--------------------------------------------------------

  ALTER TABLE "DHIA"."SPONSORISER" ADD CONSTRAINT "SPONSORISER_FK1" FOREIGN KEY ("IDEVENT")
	  REFERENCES "DHIA"."EVENEMENT" ("ID_EVENT") ENABLE;
  ALTER TABLE "DHIA"."SPONSORISER" ADD CONSTRAINT "SPONSORISER_FK2" FOREIGN KEY ("IDASSOCIATION")
	  REFERENCES "DHIA"."ASSOCIATION" ("ID") ENABLE;
